-- +goose Up
CREATE TABLE posts (
  id UUID PRIMARY KEY,
  feed_id UUID REFERENCES feeds(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL UNIQUE, 
  description TEXT,
  published_at DATE NOT NULL DEFAULT CURRENT_DATE


);

-- +goose Down
DROP TABLE posts;